#ifndef __MYCONFIG_H
#define __MYCONFIG_H

#define MYCONFIG_LED_PIN GPIO_NUM_4
#define MYCONFIG_CAMERA_PIN GPIO_NUM_2
#define MYCONFIG_WIFI_RESET_PIN GPIO_NUM_12

#define MYCONFIG_DETECT_API_URL "https://trash.sipc115.com/detect"

#define MYCONFIG_MQTT_BROKER "mqtt://116.198.201.236:1883/"

#define MYCONFIG_UART_HMI_BAUDRATE 115200

#define MYCONFIG_HMI_TX_PIN GPIO_NUM_13
#define MYCONFIG_HMI_RX_PIN GPIO_NUM_14

#define MYCONFIG_UART_TX_PIN GPIO_NUM_15
#define MYCONFIG_UART_RX_PIN GPIO_NUM_16

#define MYCONFIG_UART_BUF_SIZE 512

#define MYCONFIG_USE_FLASH_LED 1

#endif