/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CenterTask: typeof import('./src/components/CenterTask.vue')['default']
    DataList: typeof import('./src/components/DataList.vue')['default']
    DataPredict: typeof import('./src/components/DataPredict.vue')['default']
    DataVisual: typeof import('./src/components/DataVisual.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EnrolIt: typeof import('./src/components/EnrolIt.vue')['default']
    ForgetPassword: typeof import('./src/components/ForgetPassword.vue')['default']
    LoginIt: typeof import('./src/components/LoginIt.vue')['default']
    PersonalCenter: typeof import('./src/components/PersonalCenter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WarningBox: typeof import('./src/components/WarningBox.vue')['default']
  }
}
